### ISSUE TITLE
SQLITE_BUSY failures when persisting to disk

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-go#27]
This seems to be a new problem in the latest, unreleased bits. I don't recall seeing this prior to https://github.com/microsoft/durabletask-go/pull/17. I definitely missed it since most of my testing has been with an in-memory database.

```
INFO: 2023/07/12 22:17:35 worker started with backend sqlite::taskhub.sqlite3
server listening at 127.0.0.1:4001
DEBUG: 2023/07/12 22:17:35 orchestration-processor: waiting for new work items...
DEBUG: 2023/07/12 22:17:35 activity-processor: waiting for new work items...
ERROR: 2023/07/12 22:17:35 activity-processor: failed to fetch work item: failed to query for activity work-items: database is locked (5) (SQLITE_BUSY)
ERROR: 2023/07/12 22:17:35 unexpected worker error: failed to query for activity work-items: database is locked (5) (SQLITE_BUSY). Adding 5 extra seconds of backoff.
```

The problem seems persistent as well. My assumption is that it doesn't like multiple threads accessing the database concurrently, but this seems strange since I was under the impression that SQLite supported multithreading natively.

FYI @ItalyPaleAle in case you're familiar with this SQLite error.

**Comment by ItalyPaleAle** [comment]
@cgillum Yes I actually happen to be familiar with this SQLite error.

Your assumption is correct. When performing write operations, SQLite takes a lock on the entire database.

The most interesting aspect however is that by default, if the database is locked SQLite returns a SQLITE_BUSY error and doesn't wait.

You can change that by setting some options in the DSN: https://github.com/microsoft/durabletask-go/blob/460a8a64a386d46406ddbb6a54449a9b165457ba/backend/sqlite/sqlite.go

You will need to set in the DSN `?_pragma=busy_timeout(5000)` where 5000 is the maximum wait timeout in milliseconds (so in this case, you get SQLITE_BUSY only if it waits for more than 5s)

You can also see what we do in Dapr: https://github.com/dapr/components-contrib/blob/1ab15ef04ba571ff7c7c51b299d77afaa4565071/state/sqlite/sqlite_dbaccess.go (look for `getConnectionString`)

A few other things I recommend:

- Set `?_txlock=immediate`
- For databases on file:
   -  I also strongly recommend enabling the WAL with `?_pragma=journal_mode(WAL)`
- For in-memory databases:
   - The journal must be `?_pragma=journal_mode(MEMORY)` (only allowed option besides `OFF` which disables transactions entirely)
   - I recommend also setting `?cache=shared` to make multiple connections able to access the same data

**Comment by cgillum** [comment]
@ItalyPaleAle thanks - I'll look into this right away.

Just to help complete the picture in my head, do you think that [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3) was already doing the equivalent by default? I don't recall having this issue previously, so I'm curious why it's happening now.

**Comment by ItalyPaleAle** [comment]
>  do you think that [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3) was already doing the equivalent by default?

Good question. Looks like it may have used a 5,000ms wait time by default: 

https://github.com/mattn/go-sqlite3/blob/f08f1b6b9ce62b2496d8d64df26c1e278887bc1c/sqlite3.go#L1084

> Also, on reading the [SQL_BUSY](https://www.sqlite.org/rescode.html#busy) documentation, it suggests that this is expected when there are multiple processes/connections reading the database concurrently. There's only one process involved

In Go, the database/sql package normally keeps a pool of connections (that's also why I recommended setting `?cache=shared` when using in-memory DBs). If multiple goroutines are calling the DB at the same time, they will use a different connection.

**Comment by cgillum** [comment]
I did a bit more reading on the issue, and it seems the simplest solution might be to do the following:

```go
db.SetMaxOpenConns(1)
```

It turns out I was already doing this when using the in-memory provider. I just now tried setting this in all cases and my battery of tests are now running reliably again. I think I'll go with this for now to unblock the release.

**Comment by ItalyPaleAle** [comment]
Yes that would fix both the wait timeout and the `?cache=shared` option when using in-memory. But will make access to the DB single-threaded and possibly hurt performance.

In Dapr we use the options above and we are able to get multiple goroutines to access the DB concurrently.

**Comment by cgillum** [comment]
Interesting note [here in the sqlite docs](https://www.sqlite.org/sharedcache.html#use_of_shared_cache_is_discouraged) that shared-cache mode is now discouraged.

> Shared-cache mode is an obsolete feature. The use of shared-cache mode is discouraged. Most use cases for shared-cache are better served by [WAL mode](https://www.sqlite.org/wal.html).
