### ISSUE TITLE
Is this project production ready?

### ISSUE THREAD

**Issue by xinlifoobar** [microsoft/durabletask-go#85]

**Comment by cgillum** [comment]
In its current form, using the SQLite backend, no - it's not meant to be production ready. However, [Dapr Workflow](https://docs.dapr.io/developing-applications/building-blocks/workflow/), which internally uses this library, will be production ready as part of its 1.15 release.

**Comment by cgillum** [comment]
Happy to answer any other questions you may have, but marking this issue as closed.
